spring:
  application:
    name: cloud-auth
  cloud:
    nacos:
      discovery:
        group: DEFAULT_GROUP
        namespace: 5033fcba-72c5-4775-8d3b-3fbd0dc40dab
      config:
        server-addr: ${nacos-addrs}
        name: cloud-auth.yml
        group: DEFAULT_GROUP
        namespace: 5033fcba-72c5-4775-8d3b-3fbd0dc40dab
        refresh-enabled: true
  config:
    import:
      - optional:nacos:cloud-auth.yml
      - nacos:cloud-auth.yml
server:
  port: 8002

nacos-addrs : 127.0.0.1:8848
nacos-namespace: 5033fcba-72c5-4775-8d3b-3fbd0dc40dab

