spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hql1314BB@
    url: jdbc:mysql://127.0.0.1:3306/cloud-user?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&useSSL=false
  #2.6 有循环依赖无法启动配置方式
  main:
    allow-circular-references: true
  #提成公用
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 8
        min-idle: 4
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

JWK:
  SECRET-KEY: "CloudFramSecret" #私钥
  EXPIRATION-TIME: 60000        #有效期
  ISS: "MostSnails"             #签名

server:
  port: 8002

